services:
  sp1nwh33l:
    build: .
    volumes:
      - shared_results:/shared
    ports:
      - "127.0.0.1:6007:6007"
    environment:
      - TEST_MODE=${TEST_MODE:-}
      - PORT=6007
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6007/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  tests:
    profiles: ["testing"]
    build:
      context: ${TESTS_CONTEXT:-../tests}
      dockerfile: Dockerfile
    depends_on:
      sp1nwh33l:
        condition: service_healthy
    volumes:
      - ${TESTS_DIR:-./tests}:/usr/src/app
      - shared_results:/shared
    environment:
      - BASE_URL=http://sp1nwh33l:6007
      - SHARED_DIR=/shared
    networks:
      - default

volumes:
  shared_results:
    driver: local